apiVersion: v1
kind: Service
metadata:
  name: resonator-svc
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: resonator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resonator-sts
  labels:
     app.kubernetes.io/name: resonator-sts
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: resonator
  serviceName: resonator-svc
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: resonator
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: resonator-bot
          image: ghcr.io/loghinalexandru/resonator:latest
          imagePullPolicy: Always
          env:
            - name: BOT_TOKEN
              value: ""
            - name: SWEARS_API_URL
              value: "http://swears-svc"
            - name: LOG_LEVEL
              value: "2" #INFO
            - name: SHARD_COUNT
              value: "3"
            - name: SHARD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name